### ISSUE TITLE
Seq - task list

### ISSUE THREAD

**Issue by Wrent** [Wrent/ppr_zbs#1]
Nacist vstupni parametry
Nacist soubor do pole
Vyzkouset vsechny kombinace o velikosti a - implementace DFS nad vsemi kombinacemi
Hlidame si minimum hran (Funkce na vypocitani poctu hran mezi X a Y)
Pro soucasne minimum si pamatujeme i rozdeleni

**Comment by elexapet** [comment]
Potrebuje to jeste predelat to prohledavani aby se chovalo jako BB-DFS

**Comment by Wrent** [comment]
O víkendu to dodělám.

**Comment by Wrent** [comment]
Asi nevim, co je jeste potreba upravovat, prijde mi, ze generovanim tech kombinaci se to chova jako DFS. Nebo jde o ty navraty ze stavu, ktere jsou rovnou spatne, aby se nepocitaly? Asi by slo sledovat stupen pridavaneho a odebiraneho uzlu do kombinace a to pricitat a odecitat to od ceny puvodni kombinace a tim by se neco nemuselo vubec zkoumat.

**Comment by Wrent** [comment]
Tak upravovat tu cenu podle stupne meneneho uzle to nepujde, ono se tech uzlu nekdy meni vic a bylo by to asi prilis mnoho pocitani. Ty funkce tam pro to kazdopadne asi necham.

**Comment by Wrent** [comment]
Tak jsem tam dal alespon nejake prorezavani ve chvili, kdy se zmeni jen jeden uzel v kombinaci. Misto cele matice to prochazi jen 4krat jeden radek, takze je to urcite o poznani rychlejsi. (linear misto kvadratickeho). Snad to takhle bude stacit.

**Comment by elexapet** [comment]
Pridal jsem jeste rekurzivni reseni pro jistotu.
