### ISSUE TITLE
Posilani grafu

### ISSUE THREAD

**Issue by Wrent** [Wrent/ppr_zbs#4]
Pri posilani grafu je trochu problem s tim, ze je ve vector<bool> a vector<bool> je specialni implementace  a kazdy prvek zabira jen jeden bit, coz je sice fajn, ale diky tomu se neda spravne konvertovat na C pole, ktere bychom umeli poslat pres MPI.

Asi by slo pouzit vector<char>, pripadne neco jineho.

Na eduxu je tohle:
MPI v zásadě podporuje streamy homogenních dat. Jedna z možností, jak data po síti poslat, je vše přetypovat na typ byte (v jazyce C se jedná vlastně o typ char - MPI_CHAR) a takto natypovaná data ulozit do zprávy a tu odeslat. Po příjmu je samozřejmě potřeba provést zpětné přetypování na správné typy. Druhou možností je s daty pracovat v jejich původnim tvaru a pomocí funkci MPI_Pack (s použitím typu MPI_PACKED) data do zprávy zapakovat položku po položce. Na straně příjmu je potřeba data zase rozpakovat pomocí funkce MPI_Unpack - přesně v tom samém pořadí v jakém byla data poslána.

Vice zde http://stackoverflow.com/questions/670308/alternative-to-vectorbool

**Comment by elexapet** [comment]
predelano
